version: "3"

services:
  app:
    image: drakona/php:7.4-symfony
    depends_on:
      - db
    volumes:
      - .:/srv

  apache:
    image: httpd:2.4.52
    depends_on:
      - app
    volumes:
      - .:/srv
    ports:
      - "8000:80"

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: api
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - "3307:3306"

  mailhog:
    image: mailhog/mailhog
    logging:
      driver: 'none'
    ports:
      - '8025:8025'
      - '1025:1025'

volumes:
  db-data: {}